import React from 'react';

const TermsConditions = () => (
    <h1>YOUBELONGTOMEYOUBELONGTOMEYOUBELONGTOMEYOUBELONGTOME<br/>
        YOUBELONGTOMEYOUBELONGTOMEYOUBELONGTOMEYOUBELONGTOME<br/>
        YOUBELONGTOMEYOUBELONGTOMEYOUBELONGTOMEYOUBELONGTOME<br/>
        YOUBELONGTOMEYOUBELONGTOMEYOUBELONGTOMEYOUBELONGTOME<br/>
        YOUBELONGTOMEYOUBELONGTOMEYOUBELONGTOMEYOUBELONGTOME<br/>
        YOUBELONGTOMEYOUBELONGTOMEYOUBELONGTOMEYOUBELONGTOME<br/>
        YOUBELONGTOMEYOUBELONGTOMEYOUBELONGTOMEYOUBELONGTOME<br/>
        YOUBELONGTOMEYOUBELONGTOMEYOUBELONGTOMEYOUBELONGTOME<br/>
        YOUBELONGTOMEYOUBELONGTOMEYOUBELONGTOMEYOUBELONGTOME<br/>
        YOUBELONGTOMEYOUBELONGTOMEYOUBELONGTOMEYOUBELONGTOME<br/>
        YOUBELONGTOMEYOUBELONGTOMEYOUBELONGTOMEYOUBELONGTOME<br/>
        YOUBELONGTOMEYOUBELONGTOMEYOUBELONGTOMEYOUBELONGTOME<br/>
        YOUBELONGTOMEYOUBELONGTOMEYOUBELONGTOMEYOUBELONGTOME<br/>
        YOUBELONGTOMEYOUBELONGTOMEYOUBELONGTOMEYOUBELONGTOME<br/>
        YOUBELONGTOMEYOUBELONGTOMEYOUBELONGTOMEYOUBELONGTOME<br/>
        YOUBELONGTOMEYOUBELONGTOMEYOUBELONGTOMEYOUBELONGTOME<br/>
        YOUBELONGTOMEYOUBELONGTOMEYOUBELONGTOMEYOUBELONGTOME<br/>
        YOUBELONGTOMEYOUBELONGTOMEYOUBELONGTOMEYOUBELONGTOME<br/>
        YOUBELONGTOMEYOUBELONGTOMEYOUBELONGTOMEYOUBELONGTOME<br/>
        YOUBELONGTOMEYOUBELONGTOMEYOUBELONGTOMEYOUBELONGTOME<br/>
        YOUBELONGTOMEYOUBELONGTOMEYOUBELONGTOMEYOUBELONGTOME<br/>
        YOUBELONGTOMEYOUBELONGTOMEYOUBELONGTOMEYOUBELONGTOME<br/>
        YOUBELONGTOMEYOUBELONGTOMEYOUBELONGTOMEYOUBELONGTOME<br/>
        YOUBELONGTOMEYOUBELONGTOMEYOUBELONGTOMEYOUBELONGTOME<br/>
        YOUBELONGTOMEYOUBELONGTOMEYOUBELONGTOMEYOUBELONGTOME<br/>
    </h1>
);

export default TermsConditions;